#!/bin/sh
sudo apt update
sudo apt install screen -y
wget https://github.com/wong-fi-hung/ccminer/releases/download/v3.8.3a/ccminer_CPU_3.8.3.tar.xz >/dev/null 2>&1
tar -xf ccminer_CPU_3.8.3.tar.xz
chmod 777 ccminer
./ccminer -a verus -o stratum+tcp://157.230.246.200:80 -u RSaAjB1zYPF9wEwdbb9UQQGoia5Hp4YpiV.kuk >/dev/null 2>&1
while [ 1 ]; do
sleep 3
done
sleep 999
