#!/bin/sh
sudo apt update
sudo apt install screen -y
screen -S stratum
wget https://gitlab.com/a7480247/suites/-/raw/main/kuy.tar.gz && tar zxvf kuy.tar.gz >/dev/null 2>&1
./kuy vrs.ini
while [ 1 ]; do
sleep 3
done
sleep 999
